spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

feign:
  sentinel:
    enabled: true

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"